-- Crear base de datos
CREATE DATABASE IF NOT EXISTS JuegoAhorcado;
USE JuegoAhorcado;

-- Tabla: USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY
);

-- Tabla: ADMINISTRADOR
CREATE TABLE ADMINISTRADOR (
    ID_USUARIO INT PRIMARY KEY,
    NIVEL VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- Tabla: JUGADOR
CREATE TABLE JUGADOR (
    ID_USUARIO INT PRIMARY KEY,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- Tabla: CUOTA
CREATE TABLE CUOTA (
    ID_CUOTA INT PRIMARY KEY,
    TIPO VARCHAR(50),
    IMPORTE DECIMAL(10,2)
);

-- Tabla: PARTIDA
CREATE TABLE PARTIDA (
    ID_PARTIDA INT PRIMARY KEY,
    DURACION_PARTIDA INT
);

-- Tabla intermedia: JUGADOR_PARTIDA (relación muchos a muchos)
CREATE TABLE JUGADOR_PARTIDA (
    ID_USUARIO INT,
    ID_PARTIDA INT,
    PRIMARY KEY (ID_USUARIO, ID_PARTIDA),
    FOREIGN KEY (ID_USUARIO) REFERENCES JUGADOR(ID_USUARIO),
    FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDA(ID_PARTIDA)
);

-- Tabla: JUEGO
CREATE TABLE JUEGO (
    ID_JUEGO INT PRIMARY KEY
);

-- Tabla: PALABRA_FRASE
CREATE TABLE PALABRA_FRASE (
    ID_PALABRA INT PRIMARY KEY
);

-- Tabla: IDIOMA
CREATE TABLE IDIOMA (
    ID_IDIOMA INT PRIMARY KEY
);

-- Tabla: HISTORICO
CREATE TABLE HISTORICO (
    ID_HISTORICO INT PRIMARY KEY,
    ID_JUEGO INT,
    ID_PALABRA INT,
    ID_IDIOMA INT,
    FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO(ID_JUEGO),
    FOREIGN KEY (ID_PALABRA) REFERENCES PALABRA_FRASE(ID_PALABRA),
    FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA(ID_IDIOMA)
);
